### PR TITLE
support guzzle version 7

### PR DESCRIPTION
**Pull request by rrpadilla**

### CODE REVIEW

**Comment by rrpadilla** [comment]
@Dewbud do you think we should drop 7.2?

**Comment by Dewbud** [comment]
Seems safe to, feel free to remove it from the CI workflow

**Comment by rrpadilla** [comment]
@Dewbud could you create a new [tag](https://github.com/Dewbud/CardConnect/tags)? Maybe **3.0.0** ?


Thanks.

**Comment by Dewbud** [comment]
Trying to stick to semver so, the API didn't change ended up at 2.1.0

**Pull request merged**
